-- CREATE TABLE VEGETABLES_FRUITS (
--     ID SERIAL PRIMARY KEY,  
-- 	PRODUCT_NAME VARCHAR(10) NOT NULL, 
--     TYPE VARCHAR(10) NOT NULL, 
--     COLOUR VARCHAR(10) NOT NULL,
--     CALLORIES INT CHECK (CALLORIES > 0),
--     DESCRIPTION VARCHAR(100) NOT NULL
-- );


-- INSERT INTO VEGETABLES_FRUITS(
-- 	PRODUCT_NAME,
-- 	TYPE,
-- 	COLOUR,
-- 	CALLORIES,
-- 	DESCRIPTION 
-- )
-- VALUES
-- 	('ANANAS', 'FRUIT', 'YELLOW', 300, 'SWEET, TASTY'),
--     ('APPLE', 'FRUIT', 'RED', 52, 'CRISP, JUICY'),
--     ('BANANA', 'FRUIT', 'YELLOW', 89, 'SOFT, SWEET'),
--     ('CARROT', 'VEGETABLE', 'ORANGE', 41, 'CRUNCHY, SWEET'),
--     ('SPINACH', 'VEGETABLE', 'GREEN', 23, 'LEAFY, NUTRITIOUS');



-- SELECT * 
-- FROM VEGETABLES_FRUITS

-- -- 1
-- SELECT PRODUCT_NAME
-- FROM VEGETABLES_FRUITS
-- WHERE TYPE = 'VEGETABLE' 
-- AND CALLORIES < 100


-- -- 2
-- SELECT PRODUCT_NAME
-- FROM VEGETABLES_FRUITS
-- WHERE TYPE = 'FRUIT' 
-- AND CALLORIES BETWEEN 50 AND 100




-- -- 3
-- SELECT *
-- FROM VEGETABLES_FRUITS
-- WHERE PRODUCT_NAME LIKE '%SPINACH%'

-- -- 4
-- SELECT PRODUCT_NAME
-- FROM VEGETABLES_FRUITS
-- WHERE TYPE = 'VEGETABLE' 
-- AND DESCRIPTION LIKE '%NUTRITIOUS%'



-- -- 5
-- SELECT *
-- FROM VEGETABLES_FRUITS
-- WHERE COLOUR = 'RED' OR COLOUR = 'GREEN' 


