-- CREATE TABLE VEGETABLES_FRUITS (
--     ID SERIAL PRIMARY KEY,  
-- 	PRODUCT_NAME VARCHAR(10) NOT NULL, 
--     TYPE VARCHAR(10) NOT NULL, 
--     COLOUR VARCHAR(10) NOT NULL,
--     CALLORIES INT CHECK (CALLORIES > 0),
--     DESCRIPTION VARCHAR(100) NOT NULL
-- );


-- INSERT INTO VEGETABLES_FRUITS(
-- 	PRODUCT_NAME,
-- 	TYPE,
-- 	COLOUR,
-- 	CALLORIES,
-- 	DESCRIPTION 
-- )
-- VALUES
-- 	('ANANAS', 'FRUIT', 'YELLOW', 300, 'SWEET, TASTY'),
--     ('APPLE', 'FRUIT', 'RED', 52, 'CRISP, JUICY'),
--     ('BANANA', 'FRUIT', 'YELLOW', 89, 'SOFT, SWEET'),
--     ('CARROT', 'VEGETABLE', 'ORANGE', 41, 'CRUNCHY, SWEET'),
--     ('SPINACH', 'VEGETABLE', 'GREEN', 23, 'LEAFY, NUTRITIOUS');



-- SELECT * 
-- FROM VEGETABLES_FRUITS

-- -- 1
-- SELECT COUNT(*) AS VEGETABLE_COUNT
-- FROM VEGETABLES_FRUITS
-- WHERE TYPE = 'VEGETABLE';


-- -- 2
-- SELECT COUNT(*) AS FRUIT_COUNT
-- FROM VEGETABLES_FRUITS
-- WHERE TYPE = 'FRUIT';

-- -- 3
-- SELECT COUNT(*) AS FRUIT_COUNT
-- FROM VEGETABLES_FRUITS
-- WHERE COLOUR = 'YELLOW'

-- -- 4
-- SELECT COLOUR, COUNT(*) AS COUNT
-- FROM VEGETABLES_FRUITS
-- GROUP BY COLOUR;

-- 5
-- SELECT COUNT(*) AS COUNT
-- FROM VEGETABLES_FRUITS

-- 6

-- 7


-- -- 8
-- SELECT MIN(CALLORIES)
-- FROM VEGETABLES_FRUITS;


-- -- 9
-- SELECT MAX(CALLORIES)
-- FROM VEGETABLES_FRUITS;



-- -- 10
-- SELECT AVG(CALLORIES) AS AVERAGE_CALLORIES
-- FROM VEGETABLES_FRUITS;

-- -- 11
-- SELECT *
-- FROM VEGETABLES_FRUITS
-- WHERE TYPE = 'FRUIT'
-- ORDER BY CALLORIES
-- LIMIT 1;

-- -- 12
-- SELECT *
-- FROM VEGETABLES_FRUITS
-- WHERE TYPE = 'FRUIT'
-- ORDER BY CALLORIES DESC
-- LIMIT 1;

